apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xtsx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xtsx
    app.kubernetes.io/part-of: samn
  name: devfile-sample-xtsx
  namespace: samburrai-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-xtsx
status:
  loadBalancer: {}
